donnees:
  source train: "PLEIADES"
  dataset: "object_detection"
  task: "detection"
  year: [2022]
  dep: ["972"]
  type labeler: "BDTOPO"
  buffer size: 10
  n channels train: 6
  n bands: 3
  tile size: 250
  augmentation: True
  num_workers: 5

optim:
  loss: "crossentropy"
  lr: 0.0001
  momentum: 0.9
  module: "fasterrcnn"
  batch size: 1
  max epochs: 5
  val prop: 0.25

mlflow: False
